name: Super chainsaw

on:
  push:
    paths:
    - '.github/workflows/chainsaw.yml'
  workflow_dispatch:

jobs:
  build:
    name: Random tests
    runs-on: ubuntu-latest
    env:
      COLORIZE_LOG: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: ./.github/actions/setup-env

      - name: Check for changes
        run: |
          echo "GIT_BRANCH_HYPHENS: $GIT_BRANCH_HYPHENS"
          echo "PATH: $PATH"

      - name: Use Node.js 14.15.5
        uses: actions/setup-node@v1
        with:
          node-version: 14.15.5

      - name: Install dependencies
        # sed -r 's/^..YN.{6}([│┌└] )?//'
        run: |
          echo "Hello!"
          echo "::group::Install dependencies"
          echo "Installing deps"
          yarn 2>&1 | sed -r 's/(::group::|::endgroup::)//g'
          echo "::endgroup::"
          echo "Group closed"
