name: Mac runner test

on:
  push:
    paths:
    - '.github/workflows/mac.yml'
  workflow_dispatch:

jobs:
  app-test:
    name: Run Mac test
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start docker container
        run: docker run node:14.15.5-buster-slim ls /
